require 'tiny_dyno/extensions/array'

# require "tiny_dyno/extensions/big_decimal"
# require "tiny_dyno/extensions/boolean"
# require "tiny_dyno/extensions/date"
# require "tiny_dyno/extensions/date_time"
# require "tiny_dyno/extensions/false_class"
# require "tiny_dyno/extensions/float"
# require "tiny_dyno/extensions/hash"
# require "tiny_dyno/extensions/integer"
require 'tiny_dyno/extensions/module'
# require "tiny_dyno/extensions/nil_class"
# require "tiny_dyno/extensions/object"
# require "tiny_dyno/extensions/object_id"
# require "tiny_dyno/extensions/range"
# require "tiny_dyno/extensions/regexp"
# require "tiny_dyno/extensions/set"
# require "tiny_dyno/extensions/string"
# require "tiny_dyno/extensions/symbol"
# require "tiny_dyno/extensions/time"
# require "tiny_dyno/extensions/time_with_zone"
# require "tiny_dyno/extensions/true_class"
